<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    <PackageReference Include="OpenIddict.AspNetCore" Version="7.6.0" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.6.0" />
    <PackageReference Include="OpenIddict.Validation.SystemNetHttp" Version="7.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LegacyAuthDemo.Domain\LegacyAuthDemo.Domain.csproj" />
  </ItemGroup>

</Project>
